[general]
INFURA_PROJECT_ID = "your_project_id"
INFURA_PROJECT_SECRET = "your_project_secret"
PRIVATE_KEY = "your_private_key"
ACCOUNT_ADDRESS = "your_account_address"
CONTRACT_ADDRESS = "your_contract_address"
